base:
    is_dev: false
db_info:
    host: xxxx
    port: 3306
    username: xxx
    password: xxx
    database: xxx
    type: 0
out_dir: "./model"
url_tag: json
language: 中 文
db_tag: gorm
user_gorm_model: false
simple: true
is_web_tag: true
is_web_tag_pk_hidden: false
is_foreign_key: false
is_out_sql: false
is_out_func: false
is_gui: false
is_table_name: true
is_null_to_point: false
table_prefix: ""
self_type_define: {}
out_file_name: ""
web_tag_type: 0
table_names: ""
is_column_name: false
is_out_file_by_table_name: true
is_out_page: false
